language: python
python:
  - "3.6"

services:
  - postgresql

env:
  - DJANGO=1.11.1

before_install:
  - export DJANGO_SETTINGS_MODULE=scilog.settings
  - export PYTHONPATH=$HOME/builds/CLGinc/SciLog
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements/common.txt

before_script:
  - psql -c "create user scilog with password 'scilog' createdb;" -U postgres
  - psql -c "create database scilog with owner scilog;" -U postgres

# command to run tests
script:
  - python ./mana.py migrate
  - python ./manage.py test
