language: python

python:
  - "3.6"

dist: trusty

services:
  - postgresql

addons:
  postgresql: "9.6"

before_install:
  - export DJANGO_SETTINGS_MODULE=SciLog.settings
  - export PYTHONPATH=$HOME/builds/CLGinc/SciLog
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements/common.txt

before_script:
  - psql -c "create user scilog with password 'scilog' createdb;" -U postgres
  - psql -c "create database scilog with owner scilog;" -U postgres

# command to run tests
script:
  - python ./manage.py migrate
  - python ./manage.py test

notifications:
  slack: scilog:nYS7BLN8w4XOibTuo41tVi7I
