language: python

python:
  - "3.6"

dist: trusty

branches:
  only:
  - master
  - dev

services:
  - postgresql

addons:
  postgresql: "9.6"

before_install:
  - export DJANGO_SETTINGS_MODULE=SciLog.settings
  - export PYTHONPATH=$HOME/builds/CLGinc/SciLog
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements/common.txt

before_script:
  - psql -c "create user scilog with password 'scilog' createdb;" -U postgres
  - psql -c "create database scilog with owner scilog;" -U postgres

# command to run tests
script:
  - python ./manage.py migrate
  - python ./manage.py test

notifications:
  slack:
    secure: RkFIdLTRVcOIqyAo5o0YhF3Ga1sDDZb+CI99/0AQJH53YpdmTlDrBH+SOLl2zmvefeIEcJQ8sYJ7oN/FwLx8UW6ye4uzHTbWYt4cN0XWzldL2hPA4ZvsG4osDBzNbywqC6tzKR1H7sVg63Ujfn4bpUGHWnAWJIe8pchChKg8Ye0bHSI730i77FbsTF4oJy9qtDit1kb8r7xRDJYiWdtHyQghXELnClq6vxd0x2WP7OhWmvuo2L1N2A4GB0Mjifv5Yb8/+a24Kgpb3Fxuatji+OYhul/gdIVrGgL+w4dAlYnJgU1/gvqLBgQTTf12ZQEWdvTniD+yvQ1tGYWGDHtgRjGkJmQBWfzXki+1o+aDLA7ZUuMMP+mzqMcfsUCv1lQxSrT6urS5QjRUQ4G1M8lHgkEmCb2LzDGbvc50Yk6oYbOc5bJi9nnww+PgpouTJuhk3MPzo7aPE6XP6evdrxl+jcipywLQpzTmRdWHzYlv1vGhEIvUeJSK1Zg31hgmeiYQbolddJu46uUPB1CBdrRnkYEYMsyULKGaO1FcSJ+QzMrVbZ4D76zRzUEQwyh1UxmM94XvXMKWF4NS9di8h5giSy136nzF+u8KJtQN/kBnRi3rsehOwzbm4R9WCg4Eo8JjvGUNpO9EVu2P0WQiR9T/yt9eEXPWFBAdezKT0idiB4U=
