language: python
python:
  - "3.6"
  - "3.6-dev"

services:
  - postgresql

addons:
  postgresql: "9.5"

before_install:
  - export DJANGO_SETTINGS_MODULE=SciLog.settings
  - export PYTHONPATH=$HOME/builds/CLGinc/SciLog
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements/common.txt

before_script:
  - psql -c "create user scilog with password 'scilog' createdb;" -U postgres
  - psql -c "create database scilog with owner scilog;" -U postgres

# command to run tests
script:
  - python ./manage.py migrate
  - python ./manage.py test
